import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { auth } from "./auth";
import { Providers } from "@/components/theme-provider";
import DarkModeToggle from "./_components/dark_mode_toggle";
import Link from "next/link";
import SignOutButton from "./_components/log_out_button";
import Button from "./_components/Button";
import Header from "./Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await auth();

  if(session?.user != null) {

  }

  return (
    <html lang="en">
      <body className={`bg-background mx-40 my-8 ${inter.className}`}>
        <SessionProvider session={session}>
          <Providers>
              <Header session = {session}/>
              {/* Header: auth: {` user map -> ${JSON.stringify(session?.user)}`} */}
            <div className=" min-h-[80vh] ">{children}</div>
          </Providers>
        </SessionProvider>
      </body>
    </html>
  );
}
