import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { auth } from "./auth";
import { Providers } from "@/components/theme-provider";
import DarkModeToggle from "./_components/dark_mode_toggle";
import Link from "next/link";
import SignOutButton from "./_components/log_out_button";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await auth();
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <Providers>
            <div className="flex flex-col">
              Header: auth: {` user map -> ${JSON.stringify(session?.user)}`}
              {session?.user == null ? (
                <Link href={"/signin"}>SignIn</Link>
              ) : <SignOutButton />}
              <DarkModeToggle />
            </div>
            <div className=" min-h-[90vh] ">{children}</div>
          </Providers>
        </SessionProvider>
      </body>
    </html>
  );
}
