import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { auth } from "./auth";
import { Providers } from "@/components/theme-provider";
import DarkModeToggle from "./_components/dark_mode_toggle";
import Link from "next/link";
import SignOutButton from "./_components/log_out_button";
import Button from "./_components/Button";
import Header from "./Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await auth();

  return (
    <html lang="en">
      <body
        className={`bg-background w-full flex flex-col justify-center items-center
       ${inter.className}`}
      >
        <SessionProvider session={session}>
          <Providers>
            <div className="w-9/12 pt-10">
              <Header session={session} />
              <div className=" min-h-[80vh] ">{children}</div>
            </div>
          </Providers>
        </SessionProvider>
      </body>
    </html>
  );
}
